In [4]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd().parent
DATA = ROOT / "data" / "ethereum_fraud"

eth_fraud = pd.read_csv(DATA / "ethereum-frauddetection-dataset/transaction_dataset.csv")

In [5]:
eth_fraud.shape

(9841, 51)

In [6]:
eth_fraud.head()

,Unnamed: 0,Index,Address,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,...,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name,ERC20 most sent token type,ERC20_most_rec_token_type
0,0,1,0x00009277775ac7d0d59eaad8fee3d10ac6c805e8,0,844.26,1093.71,704785.63,721,89,0,...,0.000000,1.683100e+07,271779.920000,0.0,0.0,0.0,39.0,57.0,Cofoundit,Numeraire
1,1,2,0x0002b44ddb1476db43c868bd494422ee4c136fed,0,12709.07,2958.44,1218216.73,94,8,0,...,2.260809,2.260809e+00,2.260809,0.0,0.0,0.0,1.0,7.0,Livepeer Token,Livepeer Token
2,2,3,0x0002bda54cb772d040f779e88eb453cac0daa244,0,246194.54,2434.02,516729.30,2,10,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,8.0,NaN,XENON
3,3,4,0x00038e6ba2fd5c09aedb96697c8d7b8fa6632e5e,0,10219.60,15785.09,397555.90,25,9,0,...,100.000000,9.029231e+03,3804.076893,0.0,0.0,0.0,1.0,11.0,Raiden,XENON
4,4,5,0x00062d1dd1afb6fb02540ddad9cdebfe568e0d89,0,36.61,10707.77,382472.42,4598,20,1,...,0.000000,4.500000e+04,13726.659220,0.0,0.0,0.0,6.0,27.0,StatusNetwork,EOS

In [7]:
eth_fraud.dtypes

Unnamed: 0                                                int64
Index                                                     int64
Address                                                     str
FLAG                                                      int64
Avg min between sent tnx                                float64
Avg min between received tnx                            float64
Time Diff between first and last (Mins)                 float64
Sent tnx                                                  int64
Received Tnx                                              int64
Number of Created Contracts                               int64
Unique Received From Addresses                            int64
Unique Sent To Addresses                                  int64
min value received                                      float64
max value received                                      float64
avg val received                                        float64
min val sent                                            float64
max val sent                                            float64
avg val sent                                            float64
min value sent to contract                              float64
max val sent to contract                                float64
avg value sent to contract                              float64
total transactions (including tnx to create contract      int64
total Ether sent                                        float64
total ether received                                    float64
total ether sent contracts                              float64
total ether balance                                     float64
 Total ERC20 tnxs                                       float64
 ERC20 total Ether received                             float64
 ERC20 total ether sent                                 float64
 ERC20 total Ether sent contract                        float64
 ERC20 uniq sent addr                                   float64
 ERC20 uniq rec addr                                    float64
 ERC20 uniq sent addr.1                                 float64
 ERC20 uniq rec contract addr                           float64
 ERC20 avg time between sent tnx                        float64
 ERC20 avg time between rec tnx                         float64
 ERC20 avg time between rec 2 tnx                       float64
 ERC20 avg time between contract tnx                    float64
 ERC20 min val rec                                      float64
 ERC20 max val rec                                      float64
 ERC20 avg val rec                                      float64
 ERC20 min val sent                                     float64
 ERC20 max val sent                                     float64
 ERC20 avg val sent                                     float64
 ERC20 min val sent contract                            float64
 ERC20 max val sent contract                            float64
 ERC20 avg val sent contract                            float64
 ERC20 uniq sent token name                             float64
 ERC20 uniq rec token name                              float64
 ERC20 most sent token type                                 str
 ERC20_most_rec_token_type                                  str
dtype: object

**Missing Values:**

In [8]:
eth_fraud.isna().sum().sort_values(ascending=False).head(15)

ERC20 most sent token type             2697
ERC20_most_rec_token_type               871
ERC20 avg val sent                      829
ERC20 total Ether received              829
ERC20 total ether sent                  829
ERC20 avg time between rec tnx          829
ERC20 avg time between rec 2 tnx        829
ERC20 max val rec                       829
ERC20 avg val rec                       829
ERC20 avg time between contract tnx     829
ERC20 avg time between sent tnx         829
ERC20 uniq rec addr                     829
ERC20 uniq sent addr.1                  829
ERC20 total Ether sent contract         829
ERC20 uniq sent addr                    829
dtype: int64

In [9]:
eth_fraud.isna().sum().sum()

np.int64(22635)

**Dublicate:**

In [10]:
eth_fraud.duplicated().sum()

np.int64(0)

In [11]:
eth_fraud[eth_fraud.duplicated()].head()

Empty DataFrame
Columns: [Unnamed: 0, Index, Address, FLAG, Avg min between sent tnx, Avg min between received tnx, Time Diff between first and last (Mins), Sent tnx, Received Tnx, Number of Created Contracts, Unique Received From Addresses, Unique Sent To Addresses, min value received, max value received , avg val received, min val sent, max val sent, avg val sent, min value sent to contract, max val sent to contract, avg value sent to contract, total transactions (including tnx to create contract, total Ether sent, total ether received, total ether sent contracts, total ether balance,  Total ERC20 tnxs,  ERC20 total Ether received,  ERC20 total ether sent,  ERC20 total Ether sent contract,  ERC20 uniq sent addr,  ERC20 uniq rec addr,  ERC20 uniq sent addr.1,  ERC20 uniq rec contract addr,  ERC20 avg time between sent tnx,  ERC20 avg time between rec tnx,  ERC20 avg time between rec 2 tnx,  ERC20 avg time between contract tnx,  ERC20 min val rec,  ERC20 max val rec,  ERC20 avg val rec,  ERC20 min val sent,  ERC20 max val sent,  ERC20 avg val sent,  ERC20 min val sent contract,  ERC20 max val sent contract,  ERC20 avg val sent contract,  ERC20 uniq sent token name,  ERC20 uniq rec token name,  ERC20 most sent token type,  ERC20_most_rec_token_type]
Index: []

[0 rows x 51 columns]

**Target Distribution:**

In [13]:
eth_fraud["FLAG"].value_counts()

FLAG
0    7662
1    2179
Name: count, dtype: int64

In [16]:
eth_fraud["FLAG"].value_counts(normalize=True) * 100

FLAG
0    77.857941
1    22.142059
Name: proportion, dtype: float64

In [17]:
eth_fraud.nunique().sort_values(ascending=False).head(15)

Unnamed: 0                                 9841
Address                                    9816
Time Diff between first and last (Mins)    7810
avg val received                           6767
total ether received                       6728
max val sent                               6647
max value received                         6302
Avg min between received tnx               6223
total Ether sent                           5868
avg val sent                               5854
total ether balance                        5717
Avg min between sent tnx                   5013
Index                                      4729
min val sent                               4719
min value received                         4589
dtype: int64

In [18]:
eth_fraud.columns[eth_fraud.nunique() <= 1]

Index([' ERC20 avg time between sent tnx', ' ERC20 avg time between rec tnx',
       ' ERC20 avg time between rec 2 tnx',
       ' ERC20 avg time between contract tnx', ' ERC20 min val sent contract',
       ' ERC20 max val sent contract', ' ERC20 avg val sent contract'],
      dtype='str')

In [19]:
eth_fraud.select_dtypes(include="object").columns

C:\Users\SOKRATIS\AppData\Local\Temp\ipykernel_27628\3505096525.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  eth_fraud.select_dtypes(include="object").columns

Index(['Address', ' ERC20 most sent token type', ' ERC20_most_rec_token_type'], dtype='str')