In [1]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd().parent
DATA = ROOT / "data" / "ethereum_labelled_addresses"

eth_labbeled = pd.read_csv(DATA / "labelled-ethereum-addresses/eth_addresses.csv")

In [2]:
eth_labbeled.shape

(19138, 12)

In [3]:
eth_labbeled.head(50)

,Address,Name,Account Type,Contract Type,Entity,Label,Tags,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7,Akropolis (AKRO),Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,NaN,NaN,NaN,NaN
1,0x1c74cff0376fb4031cd7492cd6db2d66c3f2c6b9,bZx Protocol Token (BZRX),Smart Contract,Token,DeFi,Legit,Token Contract,bZx,DeFi,0x Ecosystem,Trading,Liquidity
2,0x06af07097c9eeb7fd685c692751d5c66db49c215,Chai (CHAI),Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,Verified Contract,NaN,NaN,NaN
3,0xc00e94cb662c3520282e6f5717214004a7f26888,Compound (COMP),Smart Contract,Token,DeFi,Legit,DAO,Compound,Token Contract,NaN,NaN,NaN
4,0xb3319f5d18bc0d84dd1b4825dcde5d5f7266d407,Compound 0x (cZRX),Smart Contract,Token,DeFi,Legit,Token Contract,DeFi,Compound,0x Ecosystem,NaN,NaN
5,0x158079ee67fce2f58472a96584a73c7ab9ac95c1,Compound Augur (cREP),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
6,0x6c8c6b02e7b2be14d4fa6022dfd6d75921d90e4e,Compound Basic Attention Token (cBAT),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
7,0x5d3a536e4d6dbd6114cc1ead35777bab948e3643,Compound Dai (cDAI),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
8,0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5,Compound Ether (cETH),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
9,0xf5dce57282a584d2746faf1593d3121fcac444dc,Compound Sai (cSAI),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
10,0x39aa39c021dfbae8fac545936693ac917d5e7563,Compound USD Coin (cUSDC),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
11,0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9,Compound USDT (cUSDT),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
12,0xc11b1268c1a384e55c48c2391d8d480264a3a7f4,Compound Wrapped BTC (cWBTC),Smart Contract,Token,DeFi,Legit,DeFi,Compound,Token Contract,NaN,NaN,NaN
13,0x6b175474e89094c44da98b954eedeac495271d0f,Dai Stablecoin (DAI),Smart Contract,Token,DeFi,Legit,Verified Contract,Token Contract,Stablecoin,DeFi,Maker,NaN
14,0x9b869c2eaae08136c43d824ea75a2f376f1aa983,DAI-HRD (DAI-HRD),Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,Verified Contract,NaN,NaN,NaN
15,0x431ad2ff6a9c365805ebad47ee021148d6f7dbe0,dForce (DF),Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,dForce,NaN,NaN,NaN
16,0x59459a7fdf11a341bb14413cca51850f072901cc,"Etheous, Inc. (EHS)",Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,Verified Contract,NaN,NaN,NaN
17,0x80fb784b7ed66730e8b1dbd9820afd29931aab03,EthLend (LEND),Smart Contract,Token,DeFi,Legit,Token Contract,Loans,Aave,NaN,NaN,NaN
18,0x493c57c4763932315a328269e1adad09653b9081,Fulcrum DAI iToken (iDAI),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
19,0x77f973fcaf871459aa58cd81881ce453759281bc,Fulcrum ETH iToken (iETH),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
20,0x1cc9567ea2eb740824a45f8026ccf8e46973234d,Fulcrum KNC iToken (iKNC),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
21,0x1d496da96caf6b518b133736beca85d5c4f9cbc5,Fulcrum LINK iToken (iLINK),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
22,0xbd56e9477fc6997609cf45f84795efbdac642ff1,Fulcrum REP iToken (iREP),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
23,0x14094949152eddbfcd073717200da82fed8dc960,Fulcrum SAI iToken (iSAI),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
24,0x49f4592e641820e928f9919ef4abd92a719b4b49,Fulcrum sUSD iToken (iSUSD),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
25,0xf013406a0b1d544238083df0b93ad0d2cbe0f65f,Fulcrum USDC iToken (iUSDC),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
26,0xba9262578efef8b3aff7f60cd629d6cc8859c8b5,Fulcrum WBTC iToken (iWBTC),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
27,0xa7eb2bc82df18013ecc2a6c533fc29446442edee,Fulcrum ZRX iToken (iZRX),Smart Contract,Token,DeFi,Legit,DeFi,bZx,Token Contract,NaN,NaN,NaN
28,0x16de59092dae5ccf4a1e6439d611fd0653f0bd01,iearn DAI (yDAI),Smart Contract,Token,DeFi,Legit,DeFi,iearn.finance,Token Contract,Verified Contract,NaN,NaN
29,0xf61718057901f84c4eec4339ef8f0d86d2b45600,iearn SUSD (ySUSD),Smart Contract,Token,DeFi,Legit,DeFi,iearn.finance,Token Contract,Verified Contract,NaN,NaN
30,0x73a052500105205d34daf004eab301916da8190f,iearn TUSD (yTUSD),Smart Contract,Token,DeFi,Legit,DeFi,iearn.finance,Token Contract,Verified Contract,NaN,NaN
31,0xd6ad7a6750a7593e092a9b218d66c0a814a3436e,iearn USDC (yUSDC),Smart Contract,Token,DeFi,Legit,DeFi,iearn.finance,Token Contract,Verified Contract,NaN,NaN
32,0x83f798e925bcd4017eb265844fddabb448f1707d,iearn USDT (yUSDT),Smart Contract,Token,DeFi,Legit,DeFi,iearn.finance,Token Contract,Verified Contract,NaN,NaN
33,0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2,Maker (MKR),Smart Contract,Token,DeFi,Legit,Token Contract,DAO,DeFi,Maker,0x Ecosystem,NaN
34,0x04abeda201850ac0124161f037efd70c74ddc74c,NEST (NEST),Smart Contract,Token,DeFi,Legit,NEST Protocol,DeFi,Token Contract,NaN,NaN,NaN
35,0xf53ad2c6851052a81b42133467480961b2321c09,Pooled Ether (PETH),Smart Contract,Token,DeFi,Legit,Maker,Token Contract,NaN,NaN,NaN,NaN
36,0xea8b224edd3e342deb514c4176c2e72bcce6fff9,Redeemable SAI (rSAI),Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,Verified Contract,NaN,NaN,NaN
37,0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359,Sai Stablecoin v1.0 (SAI),Smart Contract,Token,DeFi,Legit,DeFi,Maker,Token Contract,Stablecoin,NaN,NaN
38,0x88c64a7d2ecc882d558dd16abc1537515a78bb7d,Shifted BTC (zBTC),Smart Contract,Token,DeFi,Legit,Ren,DeFi,Token Contract,Interoperability / Cross-Chain,NaN,NaN
39,0x8a8079c7149b8a1611e5c5d978dca3be16545f83,Synth iADA (iADA),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
40,0xf6e9b246319ea30e8c2fa2d1540aaebf6f9e1b89,Synth iBCH (iBCH),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
41,0xafd870f32ce54efdbf677466b612bf8ad164454b,Synth iBNB (iBNB),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
42,0xd6014ea05bde904448b743833ddf07c3c7837481,Synth iBTC (iBTC),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
43,0x336213e1ddfc69f4701fc3f86f4ef4a160c1159d,Synth iCEX (iCEX),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
44,0xcb98f42221b2c251a4e74a1609722ee09f0cc08e,Synth iDASH (iDASH),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
45,0x14d10003807ac60d07bb0ba82caeac8d2087c157,Synth iDEFI (iDEFI),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
46,0xf4eebdd0704021ef2a6bbe993fdf93030cd784b4,Synth iEOS (iEOS),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
47,0xd50c1746d835d2770dda3703b69187bffeb14126,Synth iETC (iETC),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
48,0xa9859874e1743a32409f75bb11549892138bba1e,Synth iETH (iETH),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN
49,0x2d7ac061fc3db53c39fe1607fb8cec1b2c162b01,Synth iLINK (iLINK),Smart Contract,Token,DeFi,Legit,Synthetix,Token Contract,Proxy Contract,NaN,NaN,NaN

In [ ]:
eth_labbeled.dtypes

Address          str
Name             str
Account Type     str
Contract Type    str
Entity           str
Label            str
Tags             str
Unnamed: 7       str
Unnamed: 8       str
Unnamed: 9       str
Unnamed: 10      str
Unnamed: 11      str
dtype: object

**Missing Values:**

In [ ]:
eth_labbeled.isna().sum().sort_values(ascending=False).head(15)

Unnamed: 11      19137
Unnamed: 10      19114
Unnamed: 9       18997
Unnamed: 8       18353
Entity           17492
Contract Type    15809
Unnamed: 7       14535
Name               170
Tags                 3
Account Type         3
Address              0
Label                0
dtype: int64

In [ ]:
eth_labbeled.isna().sum().sum()

np.int64(123613)

**Dublicates:**

In [ ]:
eth_labbeled.duplicated().sum()

np.int64(0)

**Target Distribution:**

In [ ]:
eth_labbeled["Label"].value_counts()

Label
Legit    13925
Dodgy     5212
Name: count, dtype: int64

In [ ]:
eth_labbeled["Label"].value_counts(normalize=True) * 100

Label
Legit    72.764801
Dodgy    27.235199
Name: proportion, dtype: float64

In [ ]:
eth_labbeled["Label"].unique()

<StringArray>
['Legit', 'Label', 'Dodgy']
Length: 3, dtype: str

In [ ]:
eth_labbeled[eth_labbeled["Label"] == "Label"]

,Address,Name,Account Type,Contract Type,Entity,Label,Tags,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
1127,Address,Name,Account Type,Contract Type,Entity,Label,Tags,NaN,NaN,NaN,NaN,NaN

In [ ]:
eth_labbeled = eth_labbeled[eth_labbeled["Label"] != "Label"]

In [ ]:
eth_labbeled[eth_labbeled["Label"] == "Label"]

Empty DataFrame
Columns: [Address, Name, Account Type, Contract Type, Entity, Label, Tags, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11]
Index: []