In [4]:
import pandas as pd

elliptic = pd.read_csv("../data/elliptic_plus_plus/txs_features.csv")
print(elliptic.head())

    txId  Time step  Local_feature_1  Local_feature_2  Local_feature_3  \
0   3321          1        -0.169615        -0.184668        -1.201369
1  11108          1        -0.137586        -0.184668        -1.201369
2  51816          1        -0.170103        -0.184668        -1.201369
3  68869          1        -0.114267        -0.184668        -1.201369
4  89273          1         5.202107        -0.210553        -1.756361

   Local_feature_4  Local_feature_5  Local_feature_6  Local_feature_7  \
0        -0.121970        -0.043875        -0.113002        -0.061584
1        -0.121970        -0.043875        -0.113002        -0.061584
2        -0.121970        -0.043875        -0.113002        -0.061584
3         0.028105        -0.043875        -0.113002         0.547008
4        -0.121970       260.090707        -0.113002        -0.061584

   Local_feature_8  ...  in_BTC_min  in_BTC_max  in_BTC_mean  in_BTC_median  \
0        -0.160199  ...    0.534072    0.534072     0.534072       0.534072
1        -0.127429  ...    5.611878    5.611878     5.611878       5.611878
2        -0.160699  ...    0.456608    0.456608     0.456608       0.456608
3        -0.161652  ...    0.308900    8.000000     3.102967       1.000000
4         5.335864  ...  852.164680  852.164680   852.164680     852.164680

   in_BTC_total   out_BTC_min  out_BTC_max  out_BTC_mean  out_BTC_median  \
0      0.534072  1.668990e-01     0.367074      0.266986        0.266986
1      5.611878  5.861940e-01     5.025584      2.805889        2.805889
2      0.456608  2.279902e-01     0.228518      0.228254        0.228254
3      9.308900  1.229000e+00     8.079800      4.654400        4.654400
4    852.164680  1.300000e-07    41.264036      0.065016        0.000441

   out_BTC_total
0       0.533972
1       5.611778
2       0.456508
3       9.308800
4     852.164680

[5 rows x 184 columns]

In [6]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd().parent  # because notebook is in /notebooks
DATA = ROOT / "data"

def check_csv(path: Path, n=3):
    print("\n" + "="*80)
    print("FILE:", path)
    print("EXISTS:", path.exists())
    if not path.exists():
        return
    df = pd.read_csv(path)
    print("SHAPE:", df.shape)
    print("COLUMNS (first 10):", list(df.columns[:10]))
    print("HEAD:")
    display(df.head(n))

In [7]:
check_csv(DATA / "elliptic_plus_plus" / "txs_features.csv")
check_csv(DATA / "elliptic_plus_plus" / "txs_classes.csv")
check_csv(DATA / "elliptic_plus_plus" / "txs_edgelist.csv")
check_csv(DATA / "elliptic_plus_plus" / "AddrTx_edgelist.csv")
check_csv(DATA / "elliptic_plus_plus" / "TxAddr_edgelist.csv")
check_csv(DATA / "elliptic_plus_plus" / "AddrAddr_edgelist.csv")
check_csv(DATA / "elliptic_plus_plus" / "wallets_features.csv")
check_csv(DATA / "elliptic_plus_plus" / "wallets_classes.csv")

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\txs_features.csv
EXISTS: True
SHAPE: (203769, 184)
COLUMNS (first 10): ['txId', 'Time step', 'Local_feature_1', 'Local_feature_2', 'Local_feature_3', 'Local_feature_4', 'Local_feature_5', 'Local_feature_6', 'Local_feature_7', 'Local_feature_8']
HEAD:

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,...,in_BTC_min,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total
0,3321,1,-0.169615,-0.184668,-1.201369,-0.12197,-0.043875,-0.113002,-0.061584,-0.160199,...,0.534072,0.534072,0.534072,0.534072,0.534072,0.166899,0.367074,0.266986,0.266986,0.533972
1,11108,1,-0.137586,-0.184668,-1.201369,-0.12197,-0.043875,-0.113002,-0.061584,-0.127429,...,5.611878,5.611878,5.611878,5.611878,5.611878,0.586194,5.025584,2.805889,2.805889,5.611778
2,51816,1,-0.170103,-0.184668,-1.201369,-0.12197,-0.043875,-0.113002,-0.061584,-0.160699,...,0.456608,0.456608,0.456608,0.456608,0.456608,0.227990,0.228518,0.228254,0.228254,0.456508

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\txs_classes.csv
EXISTS: True
SHAPE: (203769, 2)
COLUMNS (first 10): ['txId', 'class']
HEAD:

    txId  class
0   3321      3
1  11108      3
2  51816      3

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\txs_edgelist.csv
EXISTS: True
SHAPE: (234355, 2)
COLUMNS (first 10): ['txId1', 'txId2']
HEAD:

       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\AddrTx_edgelist.csv
EXISTS: True
SHAPE: (477117, 2)
COLUMNS (first 10): ['input_address', 'txId']
HEAD:

                        input_address       txId
0  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a  230325127
1  13Lhad3SAmu2vqYg2dxbNcxH7LE77kJu2w  230325139
2  1MAQQZn7EHP6J3erXByCciFiVcgS8ZhWqz   86875675

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\TxAddr_edgelist.csv
EXISTS: True
SHAPE: (837124, 2)
COLUMNS (first 10): ['txId', 'output_address']
HEAD:

        txId                      output_address
0  230325127  1GASxu5nMntiRKdVtTVRvEbP965G51bhHH
1  230325127  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a
2  230325139  1GFdrdgtG34GChM8SMpMwcXFc4nYbH1A5G

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\AddrAddr_edgelist.csv
EXISTS: True
SHAPE: (2868964, 2)
COLUMNS (first 10): ['input_address', 'output_address']
HEAD:

                        input_address                      output_address
0  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a  1GASxu5nMntiRKdVtTVRvEbP965G51bhHH
1  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a
2  13Lhad3SAmu2vqYg2dxbNcxH7LE77kJu2w  1GFdrdgtG34GChM8SMpMwcXFc4nYbH1A5G

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\wallets_features.csv
EXISTS: True
SHAPE: (1268260, 57)
COLUMNS (first 10): ['address', 'Time step', 'num_txs_as_sender', 'num_txs_as receiver', 'first_block_appeared_in', 'last_block_appeared_in', 'lifetime_in_blocks', 'total_txs', 'first_sent_block', 'first_received_block']
HEAD:

,address,Time step,num_txs_as_sender,num_txs_as receiver,first_block_appeared_in,last_block_appeared_in,lifetime_in_blocks,total_txs,first_sent_block,first_received_block,...,blocks_btwn_output_txs_min,blocks_btwn_output_txs_max,blocks_btwn_output_txs_mean,blocks_btwn_output_txs_median,num_addr_transacted_multiple,transacted_w_address_total,transacted_w_address_min,transacted_w_address_max,transacted_w_address_mean,transacted_w_address_median
0,111112TykSw72ztDN2WJger4cynzWYC5w,25,0.0,1.0,439586.0,439586.0,0.0,1.0,0.0,439586.0,...,0.0,0.0,0.000000,0.0,0.0,24.0,1.0,1.0,1.0,1.0
1,1111DAYXhoxZx2tsRnzimfozo783x1yC2,25,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,...,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
2,1111DAYXhoxZx2tsRnzimfozo783x1yC2,29,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,...,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\elliptic_plus_plus\wallets_classes.csv
EXISTS: True
SHAPE: (822942, 2)
COLUMNS (first 10): ['address', 'class']
HEAD:

                             address  class
0  111112TykSw72ztDN2WJger4cynzWYC5w      2
1  1111DAYXhoxZx2tsRnzimfozo783x1yC2      3
2   1111VHuXEzHaRCgXbVwojtaP7Co3QABb      2

In [8]:
check_csv(DATA / "ethereum_fraud" / "ethereum-frauddetection-dataset" / "transaction_dataset.csv")

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\ethereum_fraud\ethereum-frauddetection-dataset\transaction_dataset.csv
EXISTS: True
SHAPE: (9841, 51)
COLUMNS (first 10): ['Unnamed: 0', 'Index', 'Address', 'FLAG', 'Avg min between sent tnx', 'Avg min between received tnx', 'Time Diff between first and last (Mins)', 'Sent tnx', 'Received Tnx', 'Number of Created Contracts']
HEAD:

,Unnamed: 0,Index,Address,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,...,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name,ERC20 most sent token type,ERC20_most_rec_token_type
0,0,1,0x00009277775ac7d0d59eaad8fee3d10ac6c805e8,0,844.26,1093.71,704785.63,721,89,0,...,0.000000,1.683100e+07,271779.920000,0.0,0.0,0.0,39.0,57.0,Cofoundit,Numeraire
1,1,2,0x0002b44ddb1476db43c868bd494422ee4c136fed,0,12709.07,2958.44,1218216.73,94,8,0,...,2.260809,2.260809e+00,2.260809,0.0,0.0,0.0,1.0,7.0,Livepeer Token,Livepeer Token
2,2,3,0x0002bda54cb772d040f779e88eb453cac0daa244,0,246194.54,2434.02,516729.30,2,10,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,8.0,NaN,XENON

In [10]:
check_csv(DATA / "ethereum_labelled_addresses" / "labelled-ethereum-addresses" / "eth_addresses.csv")

================================================================================
FILE: c:\University\Year4\Thesis\AML-Thesis\data\ethereum_labelled_addresses\labelled-ethereum-addresses\eth_addresses.csv
EXISTS: True
SHAPE: (19138, 12)
COLUMNS (first 10): ['Address', 'Name', 'Account Type', 'Contract Type', 'Entity', 'Label', 'Tags', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']
HEAD:

,Address,Name,Account Type,Contract Type,Entity,Label,Tags,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7,Akropolis (AKRO),Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,NaN,NaN,NaN,NaN
1,0x1c74cff0376fb4031cd7492cd6db2d66c3f2c6b9,bZx Protocol Token (BZRX),Smart Contract,Token,DeFi,Legit,Token Contract,bZx,DeFi,0x Ecosystem,Trading,Liquidity
2,0x06af07097c9eeb7fd685c692751d5c66db49c215,Chai (CHAI),Smart Contract,Token,DeFi,Legit,DeFi,Token Contract,Verified Contract,NaN,NaN,NaN

In [11]:
tx_classes = pd.read_csv(DATA / "elliptic_plus_plus" / "txs_classes.csv")
tx_classes["class"].value_counts(dropna=False)

class
3    157205
2     42019
1      4545
Name: count, dtype: int64

In [12]:
tx_feat = pd.read_csv(DATA / "elliptic_plus_plus" / "txs_features.csv")
merged = tx_feat.merge(tx_classes, on="txId", how="left")
merged["class"].value_counts(dropna=False).head(10)

class
3    157205
2     42019
1      4545
Name: count, dtype: int64

In [13]:
eth = pd.read_csv(DATA / "ethereum_fraud" / "ethereum-frauddetection-dataset" / "transaction_dataset.csv")

eth["FLAG"].value_counts()

FLAG
0    7662
1    2179
Name: count, dtype: int64

In [14]:
eth["FLAG"].value_counts(normalize=True)

FLAG
0    0.778579
1    0.221421
Name: proportion, dtype: float64

In [ ]:
eth.isna().sum().sort_values(ascending=False).head(10)
# Missing values on the columns - normal as not all wallets have the erc20 token,

ERC20 most sent token type             2697
ERC20_most_rec_token_type               871
ERC20 avg val sent                      829
ERC20 total Ether received              829
ERC20 total ether sent                  829
ERC20 avg time between rec tnx          829
ERC20 avg time between rec 2 tnx        829
ERC20 max val rec                       829
ERC20 avg val rec                       829
ERC20 avg time between contract tnx     829
dtype: int64

Drop ERC20 token type column?
 OR Fill with "None"?
 OR Fill numeric columns with 0?
    For AML, often:
> Token type → fill with "NoToken"
>  AND Numeric ERC20 features → fill with 0

In [ ]:
eth["Address"].nunique(), len(eth)
# Dublicate rows - 25 dublicate rows, same adresses appears more times

(9816, 9841)

For wallet-level fraud detection:

Each wallet should appear once.
We probably want to:

eth = eth.drop_duplicates(subset=["Address"])

Before training.

In [27]:
labelled = pd.read_csv(DATA / "ethereum_labelled_addresses" / 
                        "labelled-ethereum-addresses" / "eth_addresses.csv")

# Drop unnamed columns
labelled = labelled.loc[:, ~labelled.columns.str.contains("^Unnamed")]

labelled.shape

(19138, 7)

In [37]:
labelled["Label"].value_counts()

Label
Legit    13925
Dodgy     5212
Name: count, dtype: int64

In [36]:
labelled["Label"].value_counts(normalize=True)

Label
Legit    0.727648
Dodgy    0.272352
Name: proportion, dtype: float64

In [34]:
labelled["Address"].nunique(), len(labelled)

(19112, 19137)

In [35]:
labelled["Label"].unique()

<StringArray>
['Legit', 'Dodgy']
Length: 2, dtype: str

In [31]:
labelled[labelled["Label"] == "Label"]

      Address  Name  Account Type  Contract Type  Entity  Label  Tags
1127  Address  Name  Account Type  Contract Type  Entity  Label  Tags

In [32]:
labelled = labelled[labelled["Label"] != "Label"]

In [33]:
labelled["Label"].value_counts()

Label
Legit    13925
Dodgy     5212
Name: count, dtype: int64

In [38]:
labelled[labelled.duplicated("Address", keep=False)].sort_values("Address")

,Address,Name,Account Type,Contract Type,Entity,Label,Tags
6459,0x05860d453c7974cbf46508c06cba14e211c629ce,EdenChain Token,Smart Contract,Token,NaN,Legit,Token Contract
2085,0x05860d453c7974cbf46508c06cba14e211c629ce,Eden Coin (EDN),Smart Contract,Token,NaN,Legit,Blockchain
295,0x059550a1ca3c46a2adb803e9e3ea4585a34f004a,Expo,Smart Contract,NaN,DeFi,Legit,dYdX
7283,0x059550a1ca3c46a2adb803e9e3ea4585a34f004a,Expo,Smart Contract,NaN,NaN,Legit,Trading
5426,0x0b7bda8ad804cb3318ae8490b984c2883ada2154,CryptoAtoms: Logic,Smart Contract,NaN,NaN,Legit,CryptoAtoms
5425,0x0b7bda8ad804cb3318ae8490b984c2883ada2154,CryptoAtoms: Logic,Smart Contract,NaN,NaN,Legit,Gaming
5420,0x26e75307fc0c021472feb8f727839531f112f317,Crypto20 Token,Smart Contract,Token,NaN,Legit,Token Contract
1952,0x26e75307fc0c021472feb8f727839531f112f317,Crypto20 (C20),Smart Contract,Token,NaN,Legit,ICO Wallets
2938,0x27f706edde3ad952ef647dd67e24e38cd0803dd6,UselessEthereumToken (UET),Smart Contract,Token,NaN,Dodgy,Compromised
18222,0x27f706edde3ad952ef647dd67e24e38cd0803dd6,Useless Ethereum Token,Smart Contract,Token,NaN,Dodgy,Compromised
4716,0x296e3345e3da85181ff279dd36e6054d73da3717,bZx Exploiter 1: Deployer,Smart Contract,NaN,NaN,Dodgy,bZx Exploit
4717,0x296e3345e3da85181ff279dd36e6054d73da3717,bZx Exploiter 1: Deployer,Smart Contract,NaN,NaN,Legit,Contract Deployer
5493,0x2984581ece53a4390d1f568673cf693139c97049,Cryptopia 2,Wallet,NaN,NaN,Dodgy,Compromised
1220,0x2984581ece53a4390d1f568673cf693139c97049,Cryptopia 2,Wallet,NaN,Exchange,Legit,Exchange
12426,0x3a306a399085f3460bbcb5b77015ab33806a10d5,InstaDApp,Smart Contract,NaN,NaN,Legit,Finance
349,0x3a306a399085f3460bbcb5b77015ab33806a10d5,InstaDApp,Smart Contract,NaN,DeFi,Legit,DeFi
16036,0x53de591dc05404ce1f6198516b62eb14bd563a3a,Spam Token: Deployer,Smart Contract,NaN,NaN,Legit,Contract Deployer
16035,0x53de591dc05404ce1f6198516b62eb14bd563a3a,Spam Token: Deployer,Smart Contract,Token,NaN,Dodgy,Spam Token
15707,0x5b67871c3a857de81a1ca0f9f7945e5670d986dc,Set: Vault,Smart Contract,NaN,NaN,Legit,Set Protocol
15706,0x5b67871c3a857de81a1ca0f9f7945e5670d986dc,Set: Vault,Wallet,NaN,NaN,Legit,Trading
1219,0x5baeac0a0417a05733884852aa068b706967e790,Cryptopia 1,Wallet,NaN,Exchange,Legit,Exchange
5492,0x5baeac0a0417a05733884852aa068b706967e790,Cryptopia 1,Wallet,NaN,NaN,Dodgy,Compromised
1091,0x745daa146934b27e3f0b6bff1a6e36b9b90fb131,DEX.AG: Proxy Contract,Wallet,NaN,Dex,Legit,Dex
1090,0x745daa146934b27e3f0b6bff1a6e36b9b90fb131,DEX.AG: Proxy Contract,Wallet,NaN,Dex,Legit,Dex
7238,0x7a6425c9b3f5521bfa5d71df710a2fb80508319b,Exchange,Smart Contract,NaN,NaN,Legit,Verified Contract
13734,0x7a6425c9b3f5521bfa5d71df710a2fb80508319b,miime: Exchange,Wallet,NaN,NaN,Legit,Marketplace
14397,0x7be8076f4ea4a4ad08075c2508e481d6c946d12b,OpenSea,Smart Contract,NaN,NaN,Legit,OpenSea
14396,0x7be8076f4ea4a4ad08075c2508e481d6c946d12b,OpenSea,Smart Contract,NaN,NaN,Legit,Marketplace
13202,0x867ffb5a3871b500f65bdfafe0136f9667deae06,LocalEthereum 1,Smart Contract,NaN,NaN,Legit,Marketplace
13203,0x867ffb5a3871b500f65bdfafe0136f9667deae06,LocalEthereum 1,Smart Contract,NaN,NaN,Legit,OTC
5498,0x9007a0421145b06a0345d55a8c0f0327f62a2224,Cryptopia Hacker 3,Wallet,NaN,NaN,Dodgy,Cryptopia Hack
5499,0x9007a0421145b06a0345d55a8c0f0327f62a2224,Cryptopia Hacker 3,Wallet,NaN,NaN,Dodgy,Heist
15482,0xa4fc358455febe425536fd1878be67ffdbdec59a,Sablier,Smart Contract,NaN,NaN,Legit,Verified Contract
15488,0xa4fc358455febe425536fd1878be67ffdbdec59a,Sablier: Real-Time Finance,Smart Contract,NaN,NaN,Legit,Finance
7071,0xa52e014b3f5cc48287c2d483a3e026c32cc76e6d,Etheroll: Contract,Smart Contract,NaN,NaN,Legit,Gambling
7072,0xa52e014b3f5cc48287c2d483a3e026c32cc76e6d,Etheroll: Contract,Smart Contract,NaN,NaN,Legit,Etheroll
5497,0xaa923cd02364bb8a4c3d6f894178d2e12231655c,Cryptopia Hacker 2,Wallet,NaN,NaN,Dodgy,Heist
5496,0xaa923cd02364bb8a4c3d6f894178d2e12231655c,Cryptopia Hacker 2,Wallet,NaN,NaN,Dodgy,Cryptopia Hack
3782,0xbceaa0040764009fdcff407e82ad1f06465fd2c4,Bancor Hacker,Wallet,NaN,NaN,Dodgy,Phish / Hack
3781,0xbceaa0040764009fdcff407e82ad1f06465fd2c4,Bancor Hacker,NaN,NaN,NaN,Dodgy,Heist
14680,0xbd6a40bb904aea5a49c59050b5395f7484a4203d,Payroll,Smart Contract,NaN,NaN,Legit,Verified Contract
15487,0xbd6a40bb904aea5a49c59050b5395f7484a4203d,Sablier: Proxy,Smart Contract,NaN,NaN,Legit,Finance
2389,0xc12d1c73ee7dc3615ba4e37e4abfdbddfa38907e,KickToken (KICK),Smart Contract,Token,NaN,Legit,Crowdfunding
12773,0xc12d1c73ee7dc3615ba4e37e4abfdbddfa38907e,KickICO Token,Smart Contract,Token,NaN,Legit,Airdrop / Distributor
5495,0xc8b759860149542a98a3eb57c14aadf59d6d89b9,Cryptopia Hacker 1,Wallet,NaN,NaN,Dodgy,Heist
5494,0xc8b759860149542a98a3eb57c14aadf59d6d89b9,Cryptopia Hacker 1,Wallet,NaN,NaN,Dodgy,Cryptopia Hack
4960,0xe814aee960a85208c3db542c53e7d4a6c8d5f60f,ChronoLogic: Day Token,Smart Contract,Token,NaN,Legit,Token Contract
2014,0xe814aee960a85208c3db542c53e7d4a6c8d5f60f,DAY (DAY),Smart Contract,Token,NaN,Legit,Smart Contract
14814,0xf4a2eff88a408ff4c4550148151c33c93442619e,Plus Token Ponzi 1,Wallet,NaN,NaN,Dodgy,Plus Token Scam
14815,0xf4a2eff88a408ff4c4550148151c33c93442619e,Plus Token Ponzi 1,Wallet,NaN,NaN,Dodgy,Heist