In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

print("Project root:", project_root)
print("src exists:", (project_root / "src").exists())

Project root: c:\University\Year4\Thesis\AML-Thesis
src exists: True

In [2]:
from src.data_loader import _load_raw_ethereum
from src.data_loader import _load_preprocessed_ethereum

eth_fraud = _load_raw_ethereum()
eth_fraud

,Unnamed: 0,Index,Address,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,...,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name,ERC20 most sent token type,ERC20_most_rec_token_type
0,0,1,0x00009277775ac7d0d59eaad8fee3d10ac6c805e8,0,844.26,1093.71,704785.63,721,89,0,...,0.000000,1.683100e+07,271779.920000,0.0,0.0,0.0,39.0,57.0,Cofoundit,Numeraire
1,1,2,0x0002b44ddb1476db43c868bd494422ee4c136fed,0,12709.07,2958.44,1218216.73,94,8,0,...,2.260809,2.260809e+00,2.260809,0.0,0.0,0.0,1.0,7.0,Livepeer Token,Livepeer Token
2,2,3,0x0002bda54cb772d040f779e88eb453cac0daa244,0,246194.54,2434.02,516729.30,2,10,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,8.0,NaN,XENON
3,3,4,0x00038e6ba2fd5c09aedb96697c8d7b8fa6632e5e,0,10219.60,15785.09,397555.90,25,9,0,...,100.000000,9.029231e+03,3804.076893,0.0,0.0,0.0,1.0,11.0,Raiden,XENON
4,4,5,0x00062d1dd1afb6fb02540ddad9cdebfe568e0d89,0,36.61,10707.77,382472.42,4598,20,1,...,0.000000,4.500000e+04,13726.659220,0.0,0.0,0.0,6.0,27.0,StatusNetwork,EOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9836,9836,2175,0xff481ca14e6c16b79fc8ab299b4d2387ec8ecdd2,1,12635.10,631.39,58748.48,4,13,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,2.0,,GSENetwork
9837,9837,2176,0xff718805bb9199ebf024ab6acd333e603ad77c85,1,0.00,0.00,0.00,0,0,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,1.0,,Blockwell say NOTSAFU
9838,9838,2177,0xff8e6af02d41a576a0c82f7835535193e1a6bccc,1,2499.44,2189.29,261601.88,67,43,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,5.0,,Free BOB Tokens - BobsRepair.com
9839,9839,2178,0xffde23396d57e10abf58bd929bb1e856c7718218,1,0.00,0.00,0.00,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9840,9840,2179,0xd624d046edbdef805c5e4140dce5fb5ec1b39a3c,1,37242.70,149.56,670817.33,18,3,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,42.0,,INS Promo1

In [3]:
eth_fraud_clean = _load_preprocessed_ethereum()
eth_fraud_clean

,class,Avg_min_between_sent_tnx,Avg_min_between_received_tnx,Time_Diff_between_first_and_last_(Mins),min_value_received,max_value_received,avg_val_received,max_val_sent,avg_val_sent,min_value_sent_to_contract,...,Total_ERC20_tnxs,ERC20_total_Ether_received,ERC20_total_Ether_sent_contract,ERC20_uniq_rec_addr,ERC20_uniq_sent_addr.1,ERC20_uniq_rec_contract_addr,ERC20_min_val_rec,ERC20_max_val_rec,ERC20_avg_val_rec,ERC20_uniq_rec_token_name
0,0,844.26,1093.71,704785.63,0.000000,45.806785,6.589513,31.220000,1.200681,0.0,...,265.0,3.558854e+07,0.0,54.0,0.0,58.0,0.0,1.500000e+07,265586.147600,57.0
1,0,12709.07,2958.44,1218216.73,0.000000,2.613269,0.385685,1.800000,0.032844,0.0,...,8.0,4.034283e+02,0.0,5.0,0.0,7.0,0.0,3.650000e+02,57.632615,7.0
2,0,246194.54,2434.02,516729.30,0.113119,1.165453,0.358906,3.538616,1.794308,0.0,...,8.0,5.215121e+02,0.0,7.0,0.0,8.0,0.0,4.428198e+02,65.189009,8.0
3,0,10219.60,15785.09,397555.90,0.000000,500.000000,99.488840,450.000000,70.001834,0.0,...,14.0,1.711105e+04,0.0,11.0,0.0,11.0,0.0,1.141223e+04,1555.550174,11.0
4,0,36.61,10707.77,382472.42,0.000000,12.802411,2.671095,9.000000,0.022688,0.0,...,42.0,1.628297e+05,0.0,23.0,0.0,27.0,0.0,9.000000e+04,4934.232147,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9290,1,0.00,0.00,8427.92,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000,0.0
9291,1,12635.10,631.39,58748.48,0.004082,12.000000,2.821060,12.200000,9.166365,0.0,...,2.0,1.337000e+00,0.0,2.0,0.0,2.0,0.0,1.337000e+00,0.668500,2.0
9292,1,2499.44,2189.29,261601.88,0.001078,21.310000,1.234192,9.500000,0.922179,0.0,...,5.0,1.503470e+03,0.0,5.0,0.0,5.0,0.0,1.500000e+03,300.693901,5.0
9293,1,0.00,0.00,0.00,0.500000,0.500000,0.500000,0.000000,0.000000,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000,0.0
9294,1,37242.70,149.56,670817.33,0.795233,18998.000000,6333.265078,1000.000000,644.427778,0.0,...,44.0,6.007075e+04,0.0,37.0,0.0,42.0,0.0,2.018061e+04,1365.244359,42.0

In [4]:
eth_fraud_clean.isna().sum()

class                                      0
Avg_min_between_sent_tnx                   0
Avg_min_between_received_tnx               0
Time_Diff_between_first_and_last_(Mins)    0
min_value_received                         0
max_value_received                         0
avg_val_received                           0
max_val_sent                               0
avg_val_sent                               0
min_value_sent_to_contract                 0
max_val_sent_to_contract                   0
avg_value_sent_to_contract                 0
total_Ether_sent                           0
total_ether_received                       0
total_ether_sent_contracts                 0
total_ether_balance                        0
Total_ERC20_tnxs                           0
ERC20_total_Ether_received                 0
ERC20_total_Ether_sent_contract            0
ERC20_uniq_rec_addr                        0
ERC20_uniq_sent_addr.1                     0
ERC20_uniq_rec_contract_addr               0
ERC20_min_val_rec                          0
ERC20_max_val_rec                          0
ERC20_avg_val_rec                          0
ERC20_uniq_rec_token_name                  0
dtype: int64

In [5]:
from src.training import run_random_forest_experiments

rf_results = run_random_forest_experiments("ethereum")
rf_results

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,ethereum,Random Forest,simple,0.946746,0.932836,0.755287,0.834725,0.980913
1,ethereum,Random Forest,simple_balanced,0.948359,0.946768,0.752266,0.838384,0.981206
2,ethereum,Random Forest,smote,0.943518,0.855346,0.821752,0.838213,0.978748

In [6]:
from src.training import run_xgboost_experiments

xgBoost_results = run_xgboost_experiments("ethereum")
xgBoost_results

c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:36:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:36:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:36:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,ethereum,XGBoost,simple,0.956966,0.953069,0.797583,0.868421,0.988217
1,ethereum,XGBoost,simple_balanced,0.960194,0.890578,0.885196,0.887879,0.988229
2,ethereum,XGBoost,smote,0.953739,0.893891,0.839879,0.866044,0.984862

In [7]:
from src.training import run_lightgbm_experiments

lightGbm_results = run_lightgbm_experiments("ethereum")
lightGbm_results

[LightGBM] [Info] Number of positive: 1325, number of negative: 6111
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001465 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4332
[LightGBM] [Info] Number of data points in the train set: 7436, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.178187 -> initscore=-1.528678
[LightGBM] [Info] Start training from score -1.528678
[LightGBM] [Info] Number of positive: 1325, number of negative: 6111
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001348 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4332
[LightGBM] [Info] Number of data points in the train set: 7436, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Info] Number of positive: 6111, number of negative: 6111
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002190 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4873
[LightGBM] [Info] Number of data points in the train set: 12222, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,ethereum,LightGBM,simple,0.959656,0.957143,0.809668,0.877250,0.986681
1,ethereum,LightGBM,simple_balanced,0.963959,0.925806,0.867069,0.895476,0.988363
2,ethereum,LightGBM,smote,0.958042,0.914754,0.842900,0.877358,0.984650

In [8]:
from src.training import run_logistic_regression_experiments

logisticRegression_results = run_logistic_regression_experiments("ethereum")
logisticRegression_results

c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,ethereum,Logistic Regression,scaled,0.822485,0.600000,0.009063,0.017857,0.775357
1,ethereum,Logistic Regression,scaled_balanced,0.553523,0.259865,0.815710,0.394161,0.769378
2,ethereum,Logistic Regression,scaled_smote,0.555137,0.260155,0.812689,0.394139,0.771751

In [9]:
from src.training import run_svm_experiments

svm_results = run_svm_experiments("ethereum")
svm_results

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,ethereum,SVM,scaled,0.824099,0.833333,0.015106,0.029674,0.858868
1,ethereum,SVM,scaled_balanced,0.670791,0.330519,0.827795,0.472414,0.825841
2,ethereum,SVM,scaled_smote,0.681549,0.338690,0.827795,0.480702,0.830399

In [10]:
from src.training import run_linear_svc_experiments

linearSvc_results = run_linear_svc_experiments("ethereum")
linearSvc_results

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,ethereum,Linear SVC,scaled,0.819796,0.000000,0.000000,0.000000,None
1,ethereum,Linear SVC,scaled_balanced,0.542227,0.255179,0.818731,0.389088,None
2,ethereum,Linear SVC,scaled_smote,0.544379,0.255218,0.812689,0.388448,None

**Elliptic**

In [11]:
from src.data_loader import _load_raw_elliptic_wallets_combined
from src.data_loader import _load_preprocessed_elliptic_wallets_combined

elliptic_combined_raw = _load_raw_elliptic_wallets_combined()

elliptic_combined_raw

,address,Time step,class,num_txs_as_sender,num_txs_as receiver,first_block_appeared_in,last_block_appeared_in,lifetime_in_blocks,total_txs,first_sent_block,...,blocks_btwn_output_txs_min,blocks_btwn_output_txs_max,blocks_btwn_output_txs_mean,blocks_btwn_output_txs_median,num_addr_transacted_multiple,transacted_w_address_total,transacted_w_address_min,transacted_w_address_max,transacted_w_address_mean,transacted_w_address_median
0,111112TykSw72ztDN2WJger4cynzWYC5w,25,2,0.0,1.0,439586.0,439586.0,0.0,1.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,24.0,1.0,1.0,1.0,1.0
1,1111DAYXhoxZx2tsRnzimfozo783x1yC2,25,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,...,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
2,1111DAYXhoxZx2tsRnzimfozo783x1yC2,29,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,...,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
3,1111DAYXhoxZx2tsRnzimfozo783x1yC2,39,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,...,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
4,1111DAYXhoxZx2tsRnzimfozo783x1yC2,39,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,...,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268255,3R2Uw5MRdSSigp8AjfT7K5es6Hupm4qLSq,31,3,1.0,1.0,451684.0,451685.0,1.0,2.0,451685.0,...,0.0,0.0,0.000000,0.0,0.0,3.0,1.0,1.0,1.0,1.0
1268256,3R2VBFbqHGC4bQ7b4ixN4jZTdv7RMbEYtf,44,3,0.0,1.0,477895.0,477895.0,0.0,1.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1268257,3R2WFmRwbDeo3rMVVu5J3jjMxAuQYYWAid,9,3,0.0,1.0,407342.0,407342.0,0.0,1.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1268258,3R2WTZGYLmbJQyoDSBftJsPRvF1mSEtkh6,3,3,0.0,1.0,395235.0,395235.0,0.0,1.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1268259,3R2bm6iqbzcVpEeFCSFarS56b56QfjyiSW,9,3,1.0,0.0,407333.0,407333.0,0.0,1.0,407333.0,...,0.0,0.0,0.000000,0.0,0.0,1.0,1.0,1.0,1.0,1.0

In [12]:
elliptic_combined_processed = _load_preprocessed_elliptic_wallets_combined()

elliptic_combined_processed

,Time step,class,num_txs_as_sender,num_txs_as receiver,first_block_appeared_in,last_block_appeared_in,lifetime_in_blocks,total_txs,first_sent_block,first_received_block,...,blocks_btwn_output_txs_min,blocks_btwn_output_txs_max,blocks_btwn_output_txs_mean,blocks_btwn_output_txs_median,num_addr_transacted_multiple,transacted_w_address_total,transacted_w_address_min,transacted_w_address_max,transacted_w_address_mean,transacted_w_address_median
0,25,0,0.0,1.0,439586.0,439586.0,0.0,1.0,0.0,439586.0,...,0.0,0.0,0.0,0.0,0.0,24.0,1.0,1.0,1.0,1.0
1,21,0,0.0,1.0,431522.0,431522.0,0.0,1.0,0.0,431522.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
2,20,0,0.0,1.0,429513.0,429513.0,0.0,1.0,0.0,429513.0,...,0.0,0.0,0.0,0.0,0.0,5.0,1.0,1.0,1.0,1.0
3,5,0,1.0,1.0,399269.0,399271.0,2.0,2.0,399271.0,399269.0,...,0.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,1.0
4,17,0,0.0,1.0,423462.0,423462.0,0.0,1.0,0.0,423462.0,...,0.0,0.0,0.0,0.0,0.0,11.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269194,38,0,0.0,1.0,465794.0,465794.0,0.0,1.0,0.0,465794.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
269195,11,0,0.0,1.0,411364.0,411364.0,0.0,1.0,0.0,411364.0,...,0.0,0.0,0.0,0.0,0.0,4.0,1.0,1.0,1.0,1.0
269196,23,0,0.0,1.0,435555.0,435555.0,0.0,1.0,0.0,435555.0,...,0.0,0.0,0.0,0.0,0.0,5.0,1.0,1.0,1.0,1.0
269197,24,0,0.0,1.0,437572.0,437572.0,0.0,1.0,0.0,437572.0,...,0.0,0.0,0.0,0.0,0.0,11.0,1.0,1.0,1.0,1.0
269198,32,0,0.0,1.0,453697.0,453697.0,0.0,1.0,0.0,453697.0,...,0.0,0.0,0.0,0.0,0.0,4.0,1.0,1.0,1.0,1.0

In [13]:
print((elliptic_combined_processed["class"] == 3).any())

False

In [14]:
print(elliptic_combined_raw.duplicated().any())

True

In [15]:
print(elliptic_combined_raw.duplicated().sum())

347569

In [16]:
print(elliptic_combined_processed.duplicated().any())

False

In [17]:
from src.training import run_random_forest_experiments

rf_results_wallets = run_random_forest_experiments("elliptic-wallets-combined")
rf_results_wallets

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-wallets-combined,Random Forest,simple,0.988447,0.962316,0.794989,0.870686,0.993882
1,elliptic-wallets-combined,Random Forest,simple_balanced,0.988020,0.959353,0.788535,0.865597,0.994365
2,elliptic-wallets-combined,Random Forest,smote,0.982634,0.776800,0.905087,0.836051,0.994107

In [18]:
xgBoost_results_walltes = run_xgboost_experiments("elliptic-wallets-combined")
xgBoost_results_walltes

c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:39:29] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:39:35] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:39:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-wallets-combined,XGBoost,simple,0.986274,0.944210,0.764617,0.844976,0.992064
1,elliptic-wallets-combined,XGBoost,simple_balanced,0.948273,0.485394,0.952544,0.643086,0.991498
2,elliptic-wallets-combined,XGBoost,smote,0.955628,0.526259,0.932043,0.672695,0.989999

In [19]:
lightGbm_results_wallets = run_lightgbm_experiments("elliptic-wallets-combined")
lightGbm_results_wallets

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 10538, number of negative: 204821
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.060186 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12074
[LightGBM] [Info] Number of data points in the train set: 215359, number of used features: 56
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.048932 -> initscore=-2.967149
[LightGBM] [Info] Start training from score -2.967149
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 10538, number of negative: 204821
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.018626 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12074
[LightGBM] [Info] Number of data points in the train set: 215359, number of used features: 56
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 204821, number of negative: 204821
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.126809 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13247
[LightGBM] [Info] Number of data points in the train set: 409642, number of used features: 56
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-wallets-combined,LightGBM,simple,0.986738,0.941582,0.777145,0.851498,0.993542
1,elliptic-wallets-combined,LightGBM,simple_balanced,0.954012,0.516057,0.963933,0.672227,0.993317
2,elliptic-wallets-combined,LightGBM,smote,0.961534,0.565147,0.927107,0.702229,0.990857

In [20]:
logisticRegression_results_wallets = run_logistic_regression_experiments("elliptic-wallets-combined")
logisticRegression_results_wallets

c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-wallets-combined,Logistic Regression,scaled,0.952099,0.584098,0.072513,0.129010,0.857215
1,elliptic-wallets-combined,Logistic Regression,scaled_balanced,0.824257,0.183126,0.749051,0.294302,0.868604
2,elliptic-wallets-combined,Logistic Regression,scaled_smote,0.825056,0.183624,0.747532,0.294827,0.870013

In [21]:
from src.training import run_linear_svc_experiments

linearSvc_results_wallets = run_linear_svc_experiments("elliptic-wallets-combined")
linearSvc_results_wallets

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-wallets-combined,Linear SVC,scaled,0.951969,0.616505,0.048216,0.089437,None
1,elliptic-wallets-combined,Linear SVC,scaled_balanced,0.832429,0.186924,0.723994,0.297133,None
2,elliptic-wallets-combined,Linear SVC,scaled_smote,0.832522,0.187322,0.725892,0.297796,None

In [22]:
from src.data_loader import _load_raw_elliptic_transactions_features
from src.data_loader import _load_raw_elliptic_transactions_classes
from src.data_loader import _load_raw_elliptic_transactions_combined

trn_features = _load_raw_elliptic_transactions_features()
trn_features

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,...,in_BTC_min,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,...,0.534072,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,...,5.611878,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,...,0.456608,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,...,0.308900,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,...,852.164680,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203764,158304003,49,-0.165622,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.156113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203765,158303998,49,-0.167040,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.157564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203766,158303966,49,-0.167040,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.157564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203767,161526077,49,-0.172212,-0.139573,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.162856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203768,194103537,49,-0.172212,-0.139573,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.162856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
trn_classes = _load_raw_elliptic_transactions_classes()
trn_classes

             txId  class
0            3321      3
1           11108      3
2           51816      3
3           68869      2
4           89273      2
...           ...    ...
203764  158304003      3
203765  158303998      3
203766  158303966      3
203767  161526077      3
203768  194103537      3

[203769 rows x 2 columns]

In [24]:
trn_features_classes_combined = _load_raw_elliptic_transactions_combined()
trn_features_classes_combined

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,...,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total,class
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,...,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972,3
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,...,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778,3
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,...,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508,3
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,...,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800,2
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,...,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203764,158304003,49,-0.165622,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.156113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203765,158303998,49,-0.167040,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.157564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203766,158303966,49,-0.167040,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.157564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203767,161526077,49,-0.172212,-0.139573,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.162856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203768,194103537,49,-0.172212,-0.139573,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.162856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [25]:
from src.data_loader import _load_preprocessed_elliptic_transactions_combined

trn_prepocessed = _load_preprocessed_elliptic_transactions_combined()
trn_prepocessed

,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,Local_feature_9,...,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total,class
0,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,-0.118555,...,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800,0
1,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,5.252974,...,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680,0
2,1,-0.172726,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.163383,-0.169201,...,0.040774,0.040774,0.040774,0.040774,9.480000e-04,0.039726,0.020337,0.020337,0.040674,0
3,1,-0.172921,-0.158783,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.163581,-0.169397,...,0.010000,0.010000,0.010000,0.010000,2.900000e-03,0.006900,0.004900,0.004900,0.009800,0
4,1,-0.169967,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160559,-0.166417,...,0.478277,0.478277,0.478277,0.478277,4.630000e-02,0.431877,0.239088,0.239088,0.478177,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46040,49,-0.039416,-0.118083,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.026985,-0.034715,...,21.175927,21.175927,21.175927,21.175927,4.005752e-02,21.135512,10.587785,10.587785,21.175569,0
46041,49,-0.050308,-0.112834,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.038129,-0.045703,...,19.449182,19.449182,19.449182,19.449182,1.000000e-02,19.438805,9.724402,9.724402,19.448805,0
46042,49,-0.154605,-0.116753,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.144840,-0.150918,...,2.914019,2.914019,2.914019,2.914019,3.886639e-01,2.524993,1.456828,1.456828,2.913657,0
46043,49,0.708000,-0.118083,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,0.737731,0.719284,...,139.670987,139.670987,139.670987,139.670987,1.018483e-01,139.568782,69.835315,69.835315,139.670630,0
46044,49,0.703311,-0.120152,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,0.732934,0.714554,...,138.927592,138.927592,138.927592,138.927592,1.400000e-01,138.787243,69.463621,69.463621,138.927243,0

In [26]:
from src.training import run_random_forest_experiments

rf_results_trn = run_random_forest_experiments("elliptic-transactions-combined")
rf_results_trn

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-combined,Random Forest,simple,0.975133,0.961905,0.477541,0.638231,0.907953
1,elliptic-transactions-combined,Random Forest,simple_balanced,0.975024,0.957346,0.477541,0.637224,0.934442
2,elliptic-transactions-combined,Random Forest,smote,0.974916,0.952830,0.477541,0.636220,0.951151

In [27]:
from src.training import run_xgboost_experiments

xgboost_results_trn = run_xgboost_experiments("elliptic-transactions-combined")
xgboost_results_trn

c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:42:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:42:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:42:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-combined,XGBoost,simple,0.975133,0.961905,0.477541,0.638231,0.941273
1,elliptic-transactions-combined,XGBoost,simple_balanced,0.971658,0.818898,0.491726,0.614476,0.941776
2,elliptic-transactions-combined,XGBoost,smote,0.975133,0.949074,0.484634,0.641628,0.943208

In [28]:
from src.training import run_lightgbm_experiments

lightGbm_results_trn = run_lightgbm_experiments("elliptic-transactions-combined")
lightGbm_results_trn

[LightGBM] [Info] Number of positive: 4122, number of negative: 32714
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.018270 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 42275
[LightGBM] [Info] Number of data points in the train set: 36836, number of used features: 181
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.111901 -> initscore=-2.071465
[LightGBM] [Info] Start training from score -2.071465
[LightGBM] [Info] Number of positive: 4122, number of negative: 32714
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017334 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 42275
[LightGBM] [Info] Number of data points in the train set: 36836, number of used features: 181
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Info] Number of positive: 32714, number of negative: 32714
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.025943 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 45458
[LightGBM] [Info] Number of data points in the train set: 65428, number of used features: 181
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-combined,LightGBM,simple,0.974916,0.957143,0.475177,0.635071,0.946200
1,elliptic-transactions-combined,LightGBM,simple_balanced,0.974590,0.912664,0.494090,0.641104,0.948937
2,elliptic-transactions-combined,LightGBM,smote,0.975676,0.954338,0.494090,0.651090,0.959254

In [29]:
from src.training import run_logistic_regression_experiments

logisticRegression_results_trn = run_logistic_regression_experiments("elliptic-transactions-combined")
logisticRegression_results_trn

c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-combined,Logistic Regression,scaled,0.955153,0.512376,0.489362,0.500605,0.862734
1,elliptic-transactions-combined,Logistic Regression,scaled_balanced,0.847975,0.181759,0.659574,0.284985,0.874600
2,elliptic-transactions-combined,Logistic Regression,scaled_smote,0.871104,0.207504,0.640662,0.313476,0.876963

In [30]:
from src.training import run_linear_svc_experiments

linearSvc_results_trn = run_linear_svc_experiments("elliptic-transactions-combined")
linearSvc_results_trn

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-combined,Linear SVC,scaled,0.962537,0.623418,0.465721,0.533153,None
1,elliptic-transactions-combined,Linear SVC,scaled_balanced,0.894994,0.240952,0.598109,0.343517,None
2,elliptic-transactions-combined,Linear SVC,scaled_smote,0.908568,0.270537,0.583924,0.369760,None